pipeline {
    agent any

    stages {
        stage('Run mvn package') {

            steps {
                dir('sbom') {
                   sh 'mvn package'
                }
            }
        }

        stage('dependencyTrackPublisher') {
            steps {
                dependencyTrackPublisher artifact: 'sbom/target/bom.xml', projectId: '735cbae3-778e-4e8b-a611-f730b855f388', synchronous: true
            }
        }
    }
}
